### ISSUE TITLE
重新起个项目名字

### ISSUE THREAD

**Issue by egoist** [stackshot/discussion#1]
总感觉「图嘈」不是太优雅 😅

**Comment by egoist** [comment]
@tucaoapp

**Comment by uu-z** [comment]
天国的stackshot....

**Comment by egoist** [comment]
@liliil 中文名呢 🙂

**Comment by egoist** [comment]
图栈、堆图 😂

**Comment by ghost** [comment]
我居然现在才看到这个 Issue 。我该去死吗？

**Comment by uu-z** [comment]
![b9fddf3b23bf30ab66dbb0aad7cd3ea938ee72b92393-ip03c5_fw658](https://user-images.githubusercontent.com/12439992/35035263-c08b1fd6-fbab-11e7-8f0c-bfbc62e67566.jpeg)

**Comment by egoist** [comment]
新名字是 Pichan，中文名皮酱 😅
